-- Lisaküsimuste migratsioon.
-- Käivita Supabase SQL Editoris enne uue koodi deployd või kohe pärast deployd.

create table if not exists public.bonus_questions (
  id bigint generated by default as identity primary key,
  question_text text not null,
  correct_answer text,
  points int not null default 3,
  sort_order int not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bonus_answers (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  question_id bigint not null references public.bonus_questions(id) on delete cascade,
  answer_text text not null default '',
  is_correct boolean not null default false,
  points int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (player_id, question_id)
);

insert into public.bonus_questions (sort_order, question_text, points, active)
select *
from (
  values
    (1, '🏆 Milline koondis tuleb maailmameistriks?', 3, true),
    (2, '⚽ Kes on turniiri suurim väravakütt?', 3, true),
    (3, '🇦🇷 Mitu väravat lööb oma viimasel suurturniiril Messi?', 3, true),
    (4, '🇵🇹 Mitu väravat lööb oma viimasel suurturniiril Ronaldo?', 3, true),
    (5, '👑 Kes võidab meie alagrupiturniiri ennustuse?', 3, true),
    (6, '🥄 Kes jääb meie alagrupiturniiri ennustuses viimaseks?', 3, true)
) as v(sort_order, question_text, points, active)
where not exists (
  select 1
  from public.bonus_questions b
  where b.sort_order = v.sort_order or b.question_text = v.question_text
);

drop trigger if exists trg_bonus_questions_updated on public.bonus_questions;
create trigger trg_bonus_questions_updated before update on public.bonus_questions
for each row execute function public.set_updated_at();

drop trigger if exists trg_bonus_answers_updated on public.bonus_answers;
create trigger trg_bonus_answers_updated before update on public.bonus_answers
for each row execute function public.set_updated_at();
