-- Jalka MM 2026 ennustustabel (Netlify Functions + Supabase)
-- Käivita Supabase SQL Editoris.

create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  username text unique not null,
  display_name text not null,
  password_hash text not null,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  stage text not null,
  match_no int not null,
  kickoff_utc timestamptz,
  home text not null,
  away text not null,
  location text,
  final_home int,
  final_away int,
  is_finished boolean not null default false,
  manual_result_override boolean not null default false,
  api_football_fixture_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists matches_match_no_uq on public.matches(match_no);

create table if not exists public.predictions (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  match_id bigint not null references public.matches(id) on delete cascade,
  pred_home int not null,
  pred_away int not null,
  points int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (player_id, match_id)
);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_players_updated on public.players;
create trigger trg_players_updated before update on public.players
for each row execute function public.set_updated_at();

drop trigger if exists trg_matches_updated on public.matches;
create trigger trg_matches_updated before update on public.matches
for each row execute function public.set_updated_at();

drop trigger if exists trg_predictions_updated on public.predictions;
create trigger trg_predictions_updated before update on public.predictions
for each row execute function public.set_updated_at();
